### ISSUE TITLE
How would we go about making the error messages custom/translateable

### ISSUE THREAD

**Issue by morksinaanab** [tiaanduplessis/tenacious-fetch#9]
Would it be easy to add a custom error message parameter? or make error codes to code against?
Now i'm checking the error string to see what kind of error it is. That is not really robust.

**Comment by tiaanduplessis** [comment]
@morksinaanab I'm not sure if I understand the question. The error returned is from the provided fetch implementation used (via `fetcher` config property). I'm only setting a custom error message for a request timeout and I'll be more than happy to update it to be more robust 😄
